### ISSUE TITLE
Slimming the image size

### ISSUE THREAD

**Issue by frol** [mitchty/alpine-ghc#1]
Naive question: I'm not very familiar with Haskell; is it really so huge by itself?

Even if the Haskell is huge, you can still slim the image size a little bit:
1. Remove `apk update` and pass `--no-cache` option ([added in Alpine 3.3](http://bugs.alpinelinux.org/issues/4905)) to `apk add`.
2. Remove `apk upgrade` since there is no need for it (the image is just a couple of days old).
3. Could you please consider moving the packages that are unrelated to GHC (like `bash`, `linux-headers`, `musl-dev`, `gmp-dev`, `zlib-dev`, `make`) to a next layer image if you need them? Are those required by GHC to build even a hello-world code?

**Comment by mitchty** [comment]
Its pretty big on its own yeah, about a gig uncompressed just for all of ghc though only ~140 megs in size when gzipped. The apks for the past few releases size as an example:

```
$ du -hs ghc-b* ghc-7*   
180M    ghc-bootstrap-7.10.2-r0.apk
180M    ghc-bootstrap-7.10.2-r1.apk
180M    ghc-bootstrap-7.10.3-r0.apk
142M    ghc-7.10.2-r0.apk
142M    ghc-7.10.2-r1.apk
142M    ghc-7.10.3-r0.apk
```

Bash will have to stay no matter what for now, its in the depends list for this reason alone. /bin/bash shebang basically and busy box sh does not like it:

```
bash-4.3# file $(which ghc)
/usr/bin/ghc: symbolic link to ghc-7.10.3
bash-4.3# file $(which ghc-7.10.3)
/usr/bin/ghc-7.10.3: Bourne-Again shell script, ASCII text executable
```

I might be able to patch the bash-isms out of the wrapper but took the lazy way out for now.

The dev packages probably aren't needed, might be leftovers from when I was porting ghc. I'd have to look to be honest, I seem to recall some things behaving very badly without those being in place. Network being the biggest offender. I erred on the side of caution to include things, but it was pretty easy to build a ghc that "worked" but basically required some dev things to be anything approaching useful. But wouldn't be hard to move them out of the depends list and push a new release.

I'll look at the new apk options, haven't updated anything to 3.3 yet, just built 1.0.0 version of stack right now and working on redoing the ghc builds to use their own llvm internally so could do some of this fairly easily and soon.

Let me test out the apk things quick and stack 1.0.0 and if that works out I'll push that out. The ghc stuff I might punt for now on while I get ghc to build with its own llvm.

**Comment by frol** [comment]
Thank you for your work! It is super helpful for my project. Please, put those notes about the requiremetns into Dockerfile just for the documentation purposes.

**Comment by mitchty** [comment]
Ok I just pushed up 1.0.0 of stack, and got rid of the apk update/upgrade bits, and looks like docker hub got to it pretty quick this time.

Updating ghc to use llvm will take a bit, it takes about 6 hours to build ghc 3 times from bootstrap to final and with llvm I'm adding another hour each time, but I'll look into if I can remove some of the depends list while I'm at it. This is mostly for getting an arm version but I figure I might as well do a lot of the same things for the x86_64 build.

I'll have a look at what my brain barely remembers about why I added those dev packages in but once I do I'll throw it in.

**Comment by mitchty** [comment]
So I could probably nuke anything from here easy enough:
https://github.com/mitchty/alpine-linux-ghc-bootstrap/blob/master/ghc/APKBUILD#L13

Let me do that quick too, you do need linux-headers for the network package to work though, found an old note on that one from when I was trying to port 7.8.

**Comment by mitchty** [comment]
Ok done, I could also nuke the WORKDIR directive. If I recall correctly that adds another layer that probably isn't needed.

**Comment by frol** [comment]
Great! Thank you! It seems that this issue is all covered at least from the image perspective. The further improvements would only be possible if the packages can be slimmed. Thus, I close this issue.
