### ISSUE TITLE
Unsatisfieable constraints: libncursesw

### ISSUE THREAD

**Issue by arianvp** [mitchty/alpine-ghc#2]
when running `apk get ghc`

```
ERROR: unsatisfiable constraints:
  so:libncursesw.so.6 (missing):
    required by: ghc-8.0.1-r0[so:libncursesw.so.6]
run: non-zero exit code: 2

```

**Comment by arianvp** [comment]
I was on an old version of alpine. Fixed

**Comment by mitchty** [comment]
Yep, think the wide library got added in Alpine Linux 3.3? Or maybe 3.4 but generally I'm just going to keep this port working with the released or just released version.
